apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgerfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgerfg
  template:
    metadata:
      labels:
        app: bgerfg
    spec:
      containers:
      - image: okteto.dev/bgerfg:latest
        name: bgerfg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "18306779-7161-4eb1-84ac-40615e24e601"
        - name: Vless_Path
          value: "/vljyejg76y"
        - name: Vmess_UUID
          value: "18306779-7161-4eb1-84ac-40615e24e601"
        - name: Vmess_Path
          value: "/vmjythgg"
        - name: Share_Path
          value: "/v2link"
